sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- "10.8.0"
install:
- npm install -g @angular/cli firebase-tools
- npm ci
script:
- ng test
deploy:
  provider: script
  script: firebase deploy --token "${FIREBASE_TOKEN}"
  skip_cleanup: true
  on:
    branch: master
