sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- lts/*
before_script:
- npm install -g @angular/cli
script:
- ng build --prod --aot
- ng test
before_deploy:
- npm install -g firebase-tools
deploy:
  provider: script
  script: firebase deploy --token "${FIREBASE_TOKEN}"
  skip_cleanup: true
  on:
    branch: master
