sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- lts/*
before_script:
- npm install -g @angular/cli
script:
- ng build --prod --aot
- ng test
deploy:
  provider: firebase
  skip_cleanup: true
  project: agmp-d4821
  on:
    branch: master
  token:
    secure: OJO9Fq4uGM7cJGC1ot23epoyOh8AYH81KuQGUaG0uOWjsZeLJr+4HHCe4jVBiGL9d5f5uGCsHadU4qdK/AzDuyrZW650i1ASS1YPvSKf40kxoSTDouvVRqRJmqghlFJdlb3np3DbkKnV0zEM+PqapMiLYI/KJbPABGwoUpgWENjDz5PL2M1CoCFra26FcRuQY2le20MwcO7nW3RhDgrnHsG0H0bzabMQdtfV+l4nmyzCINrjFmPl/K/kCygxM0By4uKOcF92jd578Za+DmLU3JaVorzn0wq1tXkzgGY/i7jhp1cXnopyMmdvW1K0ekURacDeLrsAYwaRlzDQP+8JRc61trehrpH4DlCkK79QRmTx3PF+bA91FkQ/+c9hZh5yRgVeuDXQxz5EdGBCUfUKcjSCONy9bp+mehewzctbVfMCmhGbTpffqUsY0Dl98rxsEN0RVZ82H5ei5/0FMaAxfIE9hHs5uiKpB5s9OAREEE0JuDWKdTA4RFC8CaQ/Vb+JPKofDqsHpxM8d8RcZq0vOMdFAHWgAUiXP5aD4w4F6tI5aLe2WI5K8m/O3aPH9NeObR0tScLnyT85Vk5dfK22A4e84x09k6QopcQ4UAwdMhNBA8qUkwLbjh/K+BrEBfykmJOTBFvcSJTaIGLLGxGf82q5zGWZCTWA2N/PVZIJX8I=
